/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testfx.title;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import eu.ggnet.saft.core.ui.Bind;

import static eu.ggnet.saft.core.ui.Bind.Type.TITLE;

/**
 *
 * @author oliver.guenther
 */
public class TitleJPanel extends javax.swing.JPanel {

    @Bind(TITLE)
    private final StringProperty titleProperty = new SimpleStringProperty("Der Title");

    /** Creates new form TitleJPanel */
    public TitleJPanel() {
        initComponents();
        titleTextField.setText(titleProperty.get());
        titleTextField.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                titleProperty.set(titleTextField.getText());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Title: ");
        add(jLabel1, java.awt.BorderLayout.LINE_START);
        add(titleTextField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
