/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.ggnet.saft.sample.tutorial.chapter02;

import javax.swing.JButton;

/**
 *
 * @author oliver.guenther
 */
public class MainApplicationJPanel extends javax.swing.JPanel {

    /** Creates new form MainApplicationJPanel */
    public MainApplicationJPanel() {
        initComponents();
    }

    public JButton getButtonOne() {
        return buttonOne;
    }

    public JButton getButtonTwo() {
        return buttonTwo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();

        buttonOne.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        buttonOne.setText("One");
        add(buttonOne);

        buttonTwo.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        buttonTwo.setText("Two");
        add(buttonTwo);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonTwo;
    // End of variables declaration//GEN-END:variables
}
